language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.3beta

before_install:
  - test "$TRAVIS_OS_NAME" != "osx" || brew update

install:
  - test "$TRAVIS_OS_NAME" != "osx" || brew install meson ninja glib ncurses libmpdclient

script:
  - OPTIONS="-Dtest=true -Dlyrics_screen=true -Dchat_screen=true"
  - test "$TRAVIS_OS_NAME" != "osx" || export PKG_CONFIG_PATH=/usr/local/opt/ncurses/lib/pkgconfig
  - meson . output $OPTIONS
  - ninja -v -C output
