language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      addons:
        homebrew:
          packages:
            - ccache
            - meson
            - ninja
            - glib
            - ncurses
            - libmpdclient

cache:
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew

before_cache:
  - test "$TRAVIS_OS_NAME" != "osx" || brew cleanup

before_install:
  - test "$TRAVIS_OS_NAME" != "osx" || export PATH="/usr/local/opt/ccache/libexec:$PATH"
  - test "$TRAVIS_OS_NAME" != "osx" || export HOMEBREW_NO_ANALYTICS=1

install:

before_script:
  - ccache -s

script:
  - OPTIONS="-Dlyrics_screen=true -Dchat_screen=true"
  - test "$TRAVIS_OS_NAME" != "osx" || export PKG_CONFIG_PATH=/usr/local/opt/ncurses/lib/pkgconfig
  - meson . output $OPTIONS
  - ninja -v -C output
  - ccache -s
